/**
 * gen-error-docs.ts
 * Phase 00 — G section requirement
 * Generates docs/conventions/errors.md from the ERROR_CODES registry.
 * Run: pnpm tsx scripts/gen-error-docs.ts
 * CI: pnpm gen:error-docs && git diff --exit-code
 */

import { writeFileSync } from 'node:fs'
import { join } from 'node:path'
import { pathToFileURL } from 'node:url'

// Import ErrorRegistry from shared package
// We use a dynamic require to avoid TS path issues at script level
const sharedPath = join(process.cwd(), 'packages', 'shared', 'src', 'errors', 'registry.ts')

async function main() {
  // Dynamically load the codes module via tsx
  const { ErrorRegistry } = await import(pathToFileURL(sharedPath).href) as { ErrorRegistry: Record<string, { httpStatus: number; message: string }> }

  const domains = new Map<string, Array<{ code: string; status: number; message: string }>>()

  for (const [code, meta] of Object.entries(ErrorRegistry)) {
    const domain = code.split('_')[0] ?? 'UNKNOWN'
    if (!domains.has(domain)) domains.set(domain, [])
    domains.get(domain)!.push({ code, status: meta.httpStatus, message: meta.message })
  }

  const lines: string[] = [
    '# Error Codes Registry',
    '',
    '> Auto-generated by `scripts/gen-error-docs.ts`. Do NOT edit manually.',
    `> Last generated: ${new Date().toISOString()}`,
    '',
    '## Format',
    '',
    '`DOMAIN_REASON` → HTTP status + default message',
    '',
  ]

  for (const [domain, codes] of [...domains.entries()].sort()) {
    lines.push(`## ${domain}`, '')
    lines.push('| Code | HTTP | Message |')
    lines.push('|------|------|---------|')
    for (const { code, status, message } of codes.sort((a, b) => a.code.localeCompare(b.code))) {
      lines.push(`| \`${code}\` | ${status} | ${message} |`)
    }
    lines.push('')
  }

  const outputPath = join(process.cwd(), 'docs', 'conventions', 'errors.md')
  writeFileSync(outputPath, lines.join('\n'), 'utf-8')
  console.log(`✅ Generated ${outputPath} with ${Object.keys(ErrorRegistry).length} error codes`)
}

main().catch((err: unknown) => {
  console.error('❌ gen-error-docs failed:', err)
  process.exit(1)
})
