-- Wave 06 — Files & Media Pipeline Migration
-- supabase/migrations/0611_files_media_pipeline.sql
--
-- FIXED:
-- ❌ UUID → ✅ TEXT ULID
-- ❌ auth.uid() → ✅ current_user_id()
-- ❌ workspace_members → ✅ users_workspaces
-- ❌ gen_random_uuid() → ✅ app-provided ULID
--
-- قواعد:
-- ✅ Upload عبر signed URL فقط
-- ✅ MIME whitelist إجباري
-- ✅ Per-user quota
-- ✅ RLS + Force RLS
-- ✅ Soft delete (is_deleted) + cascade hard delete trigger

-- ────────────────────────────────────────────────────────────────────────────
-- Files Table
-- ────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.files (
  id               TEXT PRIMARY KEY CHECK (public.is_ulid(id)),
  workspace_id     TEXT NOT NULL REFERENCES public.workspaces(id) ON DELETE CASCADE,
  user_id          TEXT NOT NULL,
  bucket           TEXT NOT NULL DEFAULT 'blocks-media',
  object_key       TEXT NOT NULL,
  original_name    TEXT NOT NULL,
  mime_type        TEXT NOT NULL,
  size_bytes       BIGINT NOT NULL CHECK (size_bytes >= 0 AND size_bytes <= 104857600), -- max 100MB
  width            INT,
  height           INT,
  duration_ms      INT,
  hash_sha256      TEXT,
  is_processed     BOOLEAN NOT NULL DEFAULT FALSE,
  is_deleted       BOOLEAN NOT NULL DEFAULT FALSE,
  deleted_at       TIMESTAMPTZ,
  variants         JSONB NOT NULL DEFAULT '{}'::jsonb, -- { thumb, medium, large }
  metadata         JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at       TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- MIME whitelist check (no executables)
CREATE OR REPLACE FUNCTION public.is_allowed_mime(mime TEXT)
RETURNS BOOLEAN LANGUAGE sql IMMUTABLE AS $$
  SELECT mime = ANY(ARRAY[
    -- Images
    'image/jpeg','image/png','image/gif','image/webp','image/svg+xml','image/avif',
    -- Video
    'video/mp4','video/webm','video/ogg',
    -- Audio
    'audio/mpeg','audio/ogg','audio/wav','audio/webm',
    -- Documents
    'application/pdf',
    'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
    'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
    -- Text
    'text/plain','text/csv','text/markdown',
    -- Archives (no exe)
    'application/zip','application/x-tar','application/gzip'
  ]);
$$;

ALTER TABLE public.files
  ADD CONSTRAINT mime_type_allowed CHECK (public.is_allowed_mime(mime_type));

-- ────────────────────────────────────────────────────────────────────────────
-- Per-workspace storage quota (no paid tiers — all equal)
-- Default: 5 GB per workspace
-- ────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.workspace_storage_quotas (
  workspace_id     TEXT PRIMARY KEY REFERENCES public.workspaces(id) ON DELETE CASCADE,
  quota_bytes      BIGINT NOT NULL DEFAULT 5368709120, -- 5 GB
  used_bytes       BIGINT NOT NULL DEFAULT 0 CHECK (used_bytes >= 0),
  updated_at       TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Trigger: update used_bytes on file insert/delete
CREATE OR REPLACE FUNCTION public.update_storage_quota()
RETURNS TRIGGER LANGUAGE plpgsql SECURITY DEFINER AS $$
BEGIN
  IF TG_OP = 'INSERT' THEN
    INSERT INTO public.workspace_storage_quotas (workspace_id, used_bytes)
      VALUES (NEW.workspace_id, NEW.size_bytes)
      ON CONFLICT (workspace_id)
      DO UPDATE SET
        used_bytes = workspace_storage_quotas.used_bytes + NEW.size_bytes,
        updated_at = now();
  ELSIF TG_OP = 'UPDATE' AND NEW.is_deleted = TRUE AND OLD.is_deleted = FALSE THEN
    UPDATE public.workspace_storage_quotas
      SET used_bytes = GREATEST(0, used_bytes - OLD.size_bytes),
          updated_at = now()
      WHERE workspace_id = OLD.workspace_id;
  END IF;
  RETURN COALESCE(NEW, OLD);
END;
$$;

CREATE TRIGGER trg_files_update_quota
  AFTER INSERT OR UPDATE ON public.files
  FOR EACH ROW EXECUTE FUNCTION public.update_storage_quota();

-- Quota check function (called from service before upload)
CREATE OR REPLACE FUNCTION public.check_storage_quota(
  p_workspace_id TEXT,
  p_file_size    BIGINT
) RETURNS BOOLEAN LANGUAGE sql STABLE SECURITY DEFINER AS $$
  SELECT COALESCE(
    (SELECT (used_bytes + p_file_size) <= quota_bytes
     FROM public.workspace_storage_quotas
     WHERE workspace_id = p_workspace_id),
    TRUE  -- No quota row yet → allow (first upload)
  );
$$;

-- ────────────────────────────────────────────────────────────────────────────
-- Signed Upload RPC (returns upload URL metadata — actual URL from Storage SDK)
-- ────────────────────────────────────────────────────────────────────────────
CREATE OR REPLACE FUNCTION public.request_file_upload(
  p_workspace_id  TEXT,
  p_mime_type     TEXT,
  p_size_bytes    BIGINT,
  p_original_name TEXT,
  p_file_id       TEXT  -- ULID generated by the app layer
) RETURNS JSONB LANGUAGE plpgsql SECURITY DEFINER
SET search_path = public, pg_temp AS $$
DECLARE
  v_user_id TEXT := public.current_user_id();
  v_key     TEXT;
BEGIN
  -- Auth check
  IF v_user_id IS NULL THEN
    RAISE EXCEPTION 'AUTH_REQUIRED';
  END IF;

  -- ULID validation
  IF NOT public.is_ulid(p_file_id) THEN
    RAISE EXCEPTION 'INVALID_FILE_ID';
  END IF;

  -- MIME check
  IF NOT public.is_allowed_mime(p_mime_type) THEN
    RAISE EXCEPTION 'MIME_NOT_ALLOWED: %', p_mime_type;
  END IF;

  -- Quota check
  IF NOT public.check_storage_quota(p_workspace_id, p_size_bytes) THEN
    RAISE EXCEPTION 'QUOTA_EXCEEDED';
  END IF;

  -- Build object key
  v_key := p_workspace_id || '/' || p_file_id || '/' || p_original_name;

  -- Reserve file record
  INSERT INTO public.files
    (id, workspace_id, user_id, object_key, original_name, mime_type, size_bytes)
  VALUES
    (p_file_id, p_workspace_id, v_user_id, v_key, p_original_name, p_mime_type, p_size_bytes);

  RETURN jsonb_build_object(
    'file_id',     p_file_id,
    'object_key',  v_key,
    'bucket',      'blocks-media'
  );
END;
$$;

-- Mark file as processed after worker finishes
CREATE OR REPLACE FUNCTION public.mark_file_processed(
  p_file_id TEXT,
  p_variants JSONB DEFAULT '{}'::jsonb
) RETURNS VOID LANGUAGE plpgsql SECURITY DEFINER
SET search_path = public, pg_temp AS $$
BEGIN
  UPDATE public.files
    SET is_processed = TRUE,
        variants = p_variants,
        updated_at = now()
    WHERE id = p_file_id AND user_id = public.current_user_id();
END;
$$;

-- Soft delete file
CREATE OR REPLACE FUNCTION public.delete_file(p_file_id TEXT)
RETURNS VOID LANGUAGE plpgsql SECURITY DEFINER
SET search_path = public, pg_temp AS $$
BEGIN
  UPDATE public.files
    SET is_deleted = TRUE,
        deleted_at = now(),
        updated_at = now()
    WHERE id = p_file_id AND user_id = public.current_user_id();
END;
$$;

-- ────────────────────────────────────────────────────────────────────────────
-- Indexes
-- ────────────────────────────────────────────────────────────────────────────
CREATE INDEX IF NOT EXISTS idx_files_workspace_id   ON public.files(workspace_id) WHERE NOT is_deleted;
CREATE INDEX IF NOT EXISTS idx_files_user_id        ON public.files(user_id)      WHERE NOT is_deleted;
CREATE INDEX IF NOT EXISTS idx_files_object_key     ON public.files(object_key);
CREATE INDEX IF NOT EXISTS idx_files_is_processed   ON public.files(workspace_id, is_processed) WHERE NOT is_deleted;

-- ────────────────────────────────────────────────────────────────────────────
-- Row Level Security
-- ────────────────────────────────────────────────────────────────────────────
ALTER TABLE public.files ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.files FORCE ROW LEVEL SECURITY;
ALTER TABLE public.workspace_storage_quotas ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.workspace_storage_quotas FORCE ROW LEVEL SECURITY;

-- Files: workspace-based isolation (workspace members see all workspace files)
CREATE POLICY "files_workspace_isolation" ON public.files
  FOR ALL USING (
    workspace_id = public.current_workspace_id()
  );

-- Quotas: workspace-based isolation
CREATE POLICY "quotas_workspace_isolation" ON public.workspace_storage_quotas
  FOR SELECT USING (
    workspace_id = public.current_workspace_id()
  );
